#1. ***Data Loading and Exploration***

In [83]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/AI/Assignment 2/student_data.csv')
print(df)

       Name         ID   GPA  Completed Subjects
0     Ahmed  220160081  2.44                  10
1   Mohamed  220160062  3.51                  15
2       Ali  220160069  3.23                   6
3   Youssef  220160014  2.23                  10
4     Karim  220160059  3.79                  19
5       Amr  220160088  3.66                  14
6    Khaled  220160060  2.15                   9
7     Tarek  220160034  2.93                  13
8      Omar  220160067  2.66                  12
9      Adam  220160073  2.15                  11
10   Fatima  220160025  2.66                  11
11    Aisha  220160074  2.68                  14
12     Nour  220160090  3.47                   8
13     Huda  220160019  2.26                  20
14     Rana  220160042  2.85                  20
15      Ola  220160053  2.85                  11
16    Sarah  220160086  2.47                   6
17    Salma  220160023  3.66                  15
18   Yasmin  220160045  3.63                  12
19    Malak  220160041  2.90                   9
20    Ahmed  220160049  3.36                   6
21  Mohamed  220160038  2.78                  19
22      Ali  220160055  3.53                   5
23  Youssef  220160055  2.49                   8
24    Karim  220160072  2.67                  12
25      Amr  220160055  2.99                  11
26   Khaled  220160090  3.75                   7
27    Tarek  220160050  2.47                  19
28     Omar  220160076  2.57                  11
29     Adam  220160069  2.68                  15
30   Fatima  220160088  2.47                  11
31    Aisha  220160010  3.18                   8
32     Nour  220160073  3.61                   6
33    Ahmed  220160017  3.76                  10
34     Huda  220160071  3.59                  12
35     Rana  220160033  2.12                  14
36      Ola  220160088  2.28                   6
37    Sarah  220160017  2.91                  11
38    Salma  220160086  2.83                  20
39   Yasmin  220160021  3.20                  20
40    Malak  220160066  2.79                   9
41    Ahmed  220160017  3.76                   9
42  Mohamed  220160034  3.49                  11
43      Ali  220160040  3.59                   9
44  Youssef  220160088  2.95                   5
45    Karim  220160027  2.75                  20
46      Amr  220160021  3.75                  11
47   Khaled  220160052  2.74                   7
48    Tarek  220160066  2.54                  15
49     Omar  220160058  3.93                  18
50    Ahmed  220160017  3.76                   6

i tryed to upload the student_data.csv in jupyter but  not work so i used colab and i uploaded in my drive so i use pd.read_csv to read the file

In [2]:
df.head()

      Name         ID   GPA  Completed Subjects
0    Ahmed  220160081  2.44                  10
1  Mohamed  220160062  3.51                  15
2      Ali  220160069  3.23                   6
3  Youssef  220160014  2.23                  10
4    Karim  220160059  3.79                  19

In [4]:
df.tail()

      Name         ID   GPA  Completed Subjects
46     Amr  220160021  3.75                  11
47  Khaled  220160052  2.74                   7
48   Tarek  220160066  2.54                  15
49    Omar  220160058  3.93                  18
50   Ahmed  220160017  3.76                   6

i used df.head() to print first 5 row and df.tail() to print last 5 row and i can increase output by use df.head\df.tail (num) (num = number that i want to print)

In [15]:
type(df)

pandas.core.frame.DataFrame

i used  type(df)  to know what is the class i used in df
and more info about the calss

---

In [19]:
df.dtypes

Name                   object
ID                      int64
GPA                   float64
Completed Subjects      int64
dtype: object

i used df.dtypes to know the data types all colums

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                51 non-null     object
 1   ID                  51 non-null     int64
 2   GPA                 51 non-null     float64
 3   Completed Subjects  51 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.7+ KB

and i used df.info to know is there null valuo of not
the difference between df.info and df.dtype is number of dtypes for each colums and null valuo and total numbers of colums

# 2. Data Selection and Filtering:

In [46]:
df1 = df[["Name", "GPA"]]
df1.head()

      Name   GPA
0    Ahmed  2.44
1  Mohamed  3.51
2      Ali  3.23
3  Youssef  2.23
4    Karim  3.79

i used df1 = df[["Name", "GPA"]] to create a tabel between name and gpa only

In [61]:
df1[df1["GPA"] > 2.5]

       Name   GPA
1   Mohamed  3.51
2       Ali  3.23
4     Karim  3.79
5       Amr  3.66
7     Tarek  2.93
8      Omar  2.66
10   Fatima  2.66
11    Aisha  2.68
12     Nour  3.47
14     Rana  2.85
15      Ola  2.85
17    Salma  3.66
18   Yasmin  3.63
19    Malak  2.90
20    Ahmed  3.36
21  Mohamed  2.78
22      Ali  3.53
24    Karim  2.67
25      Amr  2.99
26   Khaled  3.75
28     Omar  2.57
29     Adam  2.68
31    Aisha  3.18
32     Nour  3.61
33    Ahmed  3.76
34     Huda  3.59
37    Sarah  2.91
38    Salma  2.83
39   Yasmin  3.20
40    Malak  2.79
41    Ahmed  3.76
42  Mohamed  3.49
43      Ali  3.59
44  Youssef  2.95
45    Karim  2.75
46      Amr  3.75
47   Khaled  2.74
48    Tarek  2.54
49     Omar  3.93
50    Ahmed  3.76

In [74]:
df[(df["GPA"] > 2) & (df["Completed Subjects"] ==7)]

      Name         ID   GPA  Completed Subjects
26  Khaled  220160090  3.75                   7
47  Khaled  220160052  2.74                   7

i used df1[df1["GPA"] > 2.5] to make a condition to print number of gpa >2.5
and i used & to make one more condition

# . Data Cleaning and Manipulation:

In [77]:
df[df.duplicated()]

Empty DataFrame
Columns: [Name, ID, GPA, Completed Subjects]
Index: []

In [75]:
df.drop_duplicates(df)

       Name         ID   GPA  Completed Subjects
0     Ahmed  220160081  2.44                  10
1   Mohamed  220160062  3.51                  15
2       Ali  220160069  3.23                   6
3   Youssef  220160014  2.23                  10
4     Karim  220160059  3.79                  19
5       Amr  220160088  3.66                  14
6    Khaled  220160060  2.15                   9
7     Tarek  220160034  2.93                  13
8      Omar  220160067  2.66                  12
9      Adam  220160073  2.15                  11
10   Fatima  220160025  2.66                  11
11    Aisha  220160074  2.68                  14
12     Nour  220160090  3.47                   8
13     Huda  220160019  2.26                  20
14     Rana  220160042  2.85                  20
15      Ola  220160053  2.85                  11
16    Sarah  220160086  2.47                   6
17    Salma  220160023  3.66                  15
18   Yasmin  220160045  3.63                  12
19    Malak  220160041  2.90                   9
20    Ahmed  220160049  3.36                   6
21  Mohamed  220160038  2.78                  19
22      Ali  220160055  3.53                   5
23  Youssef  220160055  2.49                   8
24    Karim  220160072  2.67                  12
25      Amr  220160055  2.99                  11
26   Khaled  220160090  3.75                   7
27    Tarek  220160050  2.47                  19
28     Omar  220160076  2.57                  11
29     Adam  220160069  2.68                  15
30   Fatima  220160088  2.47                  11
31    Aisha  220160010  3.18                   8
32     Nour  220160073  3.61                   6
33    Ahmed  220160017  3.76                  10
34     Huda  220160071  3.59                  12
35     Rana  220160033  2.12                  14
36      Ola  220160088  2.28                   6
37    Sarah  220160017  2.91                  11
38    Salma  220160086  2.83                  20
39   Yasmin  220160021  3.20                  20
40    Malak  220160066  2.79                   9
41    Ahmed  220160017  3.76                   9
42  Mohamed  220160034  3.49                  11
43      Ali  220160040  3.59                   9
44  Youssef  220160088  2.95                   5
45    Karim  220160027  2.75                  20
46      Amr  220160021  3.75                  11
47   Khaled  220160052  2.74                   7
48    Tarek  220160066  2.54                  15
49     Omar  220160058  3.93                  18
50    Ahmed  220160017  3.76                   6

i used df[df.duplicated()] to know is there duplicated or not and print it
and use df.drop_duplicates(df) to print data without duplicat

In [79]:
df.rename(columns={"Name": "Student_Name", "ID": "Student_ID","GPA":"Grade_Point_Average"})

   Student_Name  Student_ID  Grade_Point_Average  Completed Subjects
0         Ahmed   220160081                 2.44                  10
1       Mohamed   220160062                 3.51                  15
2           Ali   220160069                 3.23                   6
3       Youssef   220160014                 2.23                  10
4         Karim   220160059                 3.79                  19
5           Amr   220160088                 3.66                  14
6        Khaled   220160060                 2.15                   9
7         Tarek   220160034                 2.93                  13
8          Omar   220160067                 2.66                  12
9          Adam   220160073                 2.15                  11
10       Fatima   220160025                 2.66                  11
11        Aisha   220160074                 2.68                  14
12         Nour   220160090                 3.47                   8
13         Huda   220160019                 2.26                  20
14         Rana   220160042                 2.85                  20
15          Ola   220160053                 2.85                  11
16        Sarah   220160086                 2.47                   6
17        Salma   220160023                 3.66                  15
18       Yasmin   220160045                 3.63                  12
19        Malak   220160041                 2.90                   9
20        Ahmed   220160049                 3.36                   6
21      Mohamed   220160038                 2.78                  19
22          Ali   220160055                 3.53                   5
23      Youssef   220160055                 2.49                   8
24        Karim   220160072                 2.67                  12
25          Amr   220160055                 2.99                  11
26       Khaled   220160090                 3.75                   7
27        Tarek   220160050                 2.47                  19
28         Omar   220160076                 2.57                  11
29         Adam   220160069                 2.68                  15
30       Fatima   220160088                 2.47                  11
31        Aisha   220160010                 3.18                   8
32         Nour   220160073                 3.61                   6
33        Ahmed   220160017                 3.76                  10
34         Huda   220160071                 3.59                  12
35         Rana   220160033                 2.12                  14
36          Ola   220160088                 2.28                   6
37        Sarah   220160017                 2.91                  11
38        Salma   220160086                 2.83                  20
39       Yasmin   220160021                 3.20                  20
40        Malak   220160066                 2.79                   9
41        Ahmed   220160017                 3.76                   9
42      Mohamed   220160034                 3.49                  11
43          Ali   220160040                 3.59                   9
44      Youssef   220160088                 2.95                   5
45        Karim   220160027                 2.75                  20
46          Amr   220160021                 3.75                  11
47       Khaled   220160052                 2.74                   7
48        Tarek   220160066                 2.54                  15
49         Omar   220160058                 3.93                  18
50        Ahmed   220160017                 3.76                   6

df.rename(columns={"Name": "Student_Name", "ID": "Student_ID","GPA":"Grade_Point_Average"}) to rename

# Data Aggregation and Grouping:

In [80]:
df.describe()

                 ID        GPA  Completed Subjects
count  5.100000e+01  51.000000           51.000000
mean   2.201601e+08   3.009216           11.686275
std    2.461422e+01   0.538404            4.527649
min    2.201600e+08   2.120000            5.000000
25%    2.201600e+08   2.615000            8.500000
50%    2.201601e+08   2.900000           11.000000
75%    2.201601e+08   3.560000           14.500000
max    2.201601e+08   3.930000           20.000000

df.describe() to print mean, median, mode, standard deviation

In [81]:
df.sort_values(by=['GPA'])

       Name         ID   GPA  Completed Subjects
35     Rana  220160033  2.12                  14
6    Khaled  220160060  2.15                   9
9      Adam  220160073  2.15                  11
3   Youssef  220160014  2.23                  10
13     Huda  220160019  2.26                  20
36      Ola  220160088  2.28                   6
0     Ahmed  220160081  2.44                  10
30   Fatima  220160088  2.47                  11
16    Sarah  220160086  2.47                   6
27    Tarek  220160050  2.47                  19
23  Youssef  220160055  2.49                   8
48    Tarek  220160066  2.54                  15
28     Omar  220160076  2.57                  11
10   Fatima  220160025  2.66                  11
8      Omar  220160067  2.66                  12
24    Karim  220160072  2.67                  12
11    Aisha  220160074  2.68                  14
29     Adam  220160069  2.68                  15
47   Khaled  220160052  2.74                   7
45    Karim  220160027  2.75                  20
21  Mohamed  220160038  2.78                  19
40    Malak  220160066  2.79                   9
38    Salma  220160086  2.83                  20
15      Ola  220160053  2.85                  11
14     Rana  220160042  2.85                  20
19    Malak  220160041  2.90                   9
37    Sarah  220160017  2.91                  11
7     Tarek  220160034  2.93                  13
44  Youssef  220160088  2.95                   5
25      Amr  220160055  2.99                  11
31    Aisha  220160010  3.18                   8
39   Yasmin  220160021  3.20                  20
2       Ali  220160069  3.23                   6
20    Ahmed  220160049  3.36                   6
12     Nour  220160090  3.47                   8
42  Mohamed  220160034  3.49                  11
1   Mohamed  220160062  3.51                  15
22      Ali  220160055  3.53                   5
34     Huda  220160071  3.59                  12
43      Ali  220160040  3.59                   9
32     Nour  220160073  3.61                   6
18   Yasmin  220160045  3.63                  12
17    Salma  220160023  3.66                  15
5       Amr  220160088  3.66                  14
26   Khaled  220160090  3.75                   7
46      Amr  220160021  3.75                  11
50    Ahmed  220160017  3.76                   6
41    Ahmed  220160017  3.76                   9
33    Ahmed  220160017  3.76                  10
4     Karim  220160059  3.79                  19
49     Omar  220160058  3.93                  18

In [82]:
df.sort_values(by='GPA', ascending=False)

       Name         ID   GPA  Completed Subjects
49     Omar  220160058  3.93                  18
4     Karim  220160059  3.79                  19
50    Ahmed  220160017  3.76                   6
33    Ahmed  220160017  3.76                  10
41    Ahmed  220160017  3.76                   9
46      Amr  220160021  3.75                  11
26   Khaled  220160090  3.75                   7
17    Salma  220160023  3.66                  15
5       Amr  220160088  3.66                  14
18   Yasmin  220160045  3.63                  12
32     Nour  220160073  3.61                   6
43      Ali  220160040  3.59                   9
34     Huda  220160071  3.59                  12
22      Ali  220160055  3.53                   5
1   Mohamed  220160062  3.51                  15
42  Mohamed  220160034  3.49                  11
12     Nour  220160090  3.47                   8
20    Ahmed  220160049  3.36                   6
2       Ali  220160069  3.23                   6
39   Yasmin  220160021  3.20                  20
31    Aisha  220160010  3.18                   8
25      Amr  220160055  2.99                  11
44  Youssef  220160088  2.95                   5
7     Tarek  220160034  2.93                  13
37    Sarah  220160017  2.91                  11
19    Malak  220160041  2.90                   9
15      Ola  220160053  2.85                  11
14     Rana  220160042  2.85                  20
38    Salma  220160086  2.83                  20
40    Malak  220160066  2.79                   9
21  Mohamed  220160038  2.78                  19
45    Karim  220160027  2.75                  20
47   Khaled  220160052  2.74                   7
29     Adam  220160069  2.68                  15
11    Aisha  220160074  2.68                  14
24    Karim  220160072  2.67                  12
10   Fatima  220160025  2.66                  11
8      Omar  220160067  2.66                  12
28     Omar  220160076  2.57                  11
48    Tarek  220160066  2.54                  15
23  Youssef  220160055  2.49                   8
30   Fatima  220160088  2.47                  11
27    Tarek  220160050  2.47                  19
16    Sarah  220160086  2.47                   6
0     Ahmed  220160081  2.44                  10
36      Ola  220160088  2.28                   6
13     Huda  220160019  2.26                  20
3   Youssef  220160014  2.23                  10
9      Adam  220160073  2.15                  11
6    Khaled  220160060  2.15                   9
35     Rana  220160033  2.12                  14

i used df.sort_values(by=['GPA']) to ascending order(by default ) and use by=['GPA'] to compare between the number in colum GPA
and now i want to descending order so i will add ascending=False to descending order

# Reference


1.  Section 3 (Artificial Intelligence (AI))
2.  https://pandas.pydata.org/

1.   https://stackoverflow.com/
2.   https://www.statology.org/